baseURL: https://deepankarm.github.io/
languageCode: en-us
title: Deepankar's Tech Blogs
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3

params:
  author: Deepankar Mahapatro
  description: Engineering Manager - Jina AI
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  socialIcons:
    - name: github
      url: https://github.com/deepankarm
    - name: linkedin
      url: https://www.linkedin.com/in/deepankar-mahapatro/

markup:
  goldmark:
    renderer:
      unsafe: true
